# Generated by Django 5.0.4 on 2024-04-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=100)),
                ("subscription", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
                ("last_payment", models.DateTimeField()),
            ],
        ),
    ]
