# Generated by Django 5.0.4 on 2024-04-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.AddField(
            model_name="customer",
            name="bandwith",
            field=models.DecimalField(
                decimal_places=2, default=2, max_digits=5, max_length=5
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="router_ip_address",
            field=models.GenericIPAddressField(default="192.168.0.1"),
            preserve_default=False,
        ),
    ]
