# Generated by Django 5.0.4 on 2024-04-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isp", "0002_remove_customer_user_customer_bandwith_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="router_ip_address",
            field=models.CharField(default="127.0.0.1", max_length=100),
        ),
    ]
