# Generated by Django 5.0.4 on 2024-04-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("isp", "0002_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
    ]
