# Generated by Django 4.2.11 on 2024-04-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0002_remove_customer_user_customer_bandwith_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='router_ip_address',
            field=models.CharField(default='127.0.0.1', max_length=100),
        ),
    ]
