# Generated by Django 5.0.4 on 2024-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isp", "0002_remove_customer_user_customer_bandwith_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="bandwith",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="customer",
            name="router_ip_address",
            field=models.CharField(default="", max_length=100),
        ),
    ]
