# Generated by Django 5.0.4 on 2024-04-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isp", "0002_alter_customer_phone_alter_customer_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=25),
        ),
    ]
