# Generated by Django 5.0.4 on 2024-05-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isp", "0003_alter_customer_bandwith_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="bandwith",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="customer",
            name="router_ip_address",
            field=models.CharField(default="127.0.0.1", max_length=100),
        ),
    ]
