# Generated by Django 5.0.4 on 2024-04-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isp", "0003_remove_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="router_ip_address",
            field=models.GenericIPAddressField(default="192.168.0.1"),
            preserve_default=False,
        ),
    ]
