# Generated by Django 5.0.4 on 2024-04-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isp", "0004_customer_router_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="bandwith",
            field=models.CharField(default=3, max_length=3),
            preserve_default=False,
        ),
    ]
