# Generated by Django 5.0.4 on 2024-05-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isp", "0004_alter_customer_bandwith_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
