# Generated by Django 5.0.4 on 2024-05-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isp", "0005_alter_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="bandwith",
            field=models.CharField(max_length=7),
        ),
    ]
