# Generated by Django 5.0.4 on 2024-05-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isp", "0006_alter_customer_bandwith"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="subscription_amount",
            field=models.IntegerField(default=1),
        ),
    ]
