# Generated by Django 5.0.4 on 2024-04-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isp", "0006_alter_customer_bandwith"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="bandwith",
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=5),
        ),
    ]
