# Generated by Django 5.0.4 on 2024-05-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("isp", "0003_alter_customer_router_ip_address"),
        ("isp", "0007_customer_subscription_amount"),
    ]

    operations = []
